name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Make sure the branch is correct (e.g., 'main')

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up Node.js environment
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'  # Adjust Node.js version if needed

    # Step 3: Install dependencies
    - name: Install dependencies
      run: npm install

    # Step 4: Build the React project
    - name: Build project
      run: npm run build

    # Step 5: Deploy to GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build  # This should point to your build directory
